import type {
    ChatCompletion,
} from "../types/chat.types.js";

export class ChatService {

    async sendMessage(
        message: string,
    ): Promise<ChatCompletion> {

        // Simulate API latency
        await new Promise((resolve) =>
            setTimeout(resolve, 1500),
        );

        return {
            content: `You said: "${message}"

This response is currently generated by the mock AI service.

In the next sprint, this service will call the OpenAI Responses API instead.`,

            provider: "mock",

            model: "mock-ai-v1",
        };
    }

}

export const chatService = new ChatService();